//
//  HomeWorker.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {

    func getCategories(completion: @escaping (Home.ResponseCategories) -> Void) {
        APIService.shared.getCategories { categories in
            completion(.init(categories: categories))
        }

    }

    func getItemsOfACategory(request: Home.RequestItemsOfACategory ,completion: @escaping (Home.ResponseItemsOfACategory) -> Void) {

        APIService.shared.getItems(categoryId: request.categoryIndexString) { items in
            completion(.init(items: items))
        }
    }

}
