//
//  HomePresenter.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class HomePresenter: HomePresenterConfiguration {
    weak var viewController: HomeDisplayConfiguration?

    // MARK: Parse and calc respnse from HomeInteractor and send simple view model to HomeViewController to be displayed

    func presentSomething(response: Home.Response) {
        let viewModel = Home.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
