//
//  HomeModels.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases


    struct RequestCategories
    {

    }

    struct RequestItemsOfACategory
    {
        var categoryIndexString: String

        init (at categoryIndexString: String) {
            self.categoryIndexString = categoryIndexString
        }
    }

    struct ResponseCategories
    {
        let categories: Categories?
    }

    struct ResponseItemsOfACategory
    {
        let items: Items?

    }

    struct ViewModelCategories
    {
        let categories: Categories
    }

    struct ViewModelItemsOfACategory
    {

        let items: Items

    }

}
