//
//  HomeRouter.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class HomeRouter: NSObject, HomeRoutingConfiguration, HomeDataPassing {

    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

// MARK: Routing (navigating to other screens)
//
//func routeToCart() {
//
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(withIdentifier: "CartViewController") as! CartViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToCart(source: dataStore!, destination: &destinationDS)
//        navigateToCart(source: viewController!, destination: destinationVC)
//
// }
//
//// MARK: Navigation to other screen
//
//func navigateToCart(source: HomeViewController, destination: CartViewController) {
//    source.navigationController?.pushViewController(destination, animated: true)
//
//}
//
//// MARK: Passing data to other screen
//
//    func passDataToCart(source: HomeDataStore, destination: inout CartViewController) {
//        destination.items = source.items
//    }
}
