//
//  HomePresenter.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class HomePresenter: HomePresenterConfiguration {
    weak var viewController: HomeDisplayConfiguration?

    func presentCategories(response: Home.ResponseCategories) {
        guard let categories = response.categories else { return }
        let viewModel = Home.ViewModelCategories(categories: categories)
        viewController?.displayCategories(viewModel: viewModel)
    }

    func presentItemsOfACategory(response: Home.ResponseItemsOfACategory) {
        guard let items = response.items else { return }
        let viewModel = Home.ViewModelItemsOfACategory(items: items)
        viewController?.displayItemsOfACategory(viewModel: viewModel)
    }


}
