//
//  HomeInteractor.swift
//  CleanFood
//
//  Created by Abdulrahman on 4/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class HomeInteractor: HomeInteractorConfiguration, HomeDataStore {
    var presenter: HomePresenterConfiguration?
    var worker: HomeWorker?
    //var name: String = ""

    // MARK: Do something (and send response to HomePresenter)

    func doSomething(request: Home.Request) {
        worker = HomeWorker()
        worker?.doSomeWork()

        let response = Home.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Home.SomethingElse.Request) {
//        worker = HomeWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Home.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
